### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by lucasff** [clauswitt/bitbucket-cli#1]
Hi!

I got the following error:

```
$ git bb account lucasfreitas ************
/Users/lucas/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- daemons (LoadError)
    from /Users/lucas/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /Users/lucas/.rvm/gems/ruby-2.1.2/gems/bitbucket-cli-0.0.2/bin/git-bb:3:in `<top (required)>'
    from /Users/lucas/.rvm/gems/ruby-2.1.2/bin/git-bb:23:in `load'
    from /Users/lucas/.rvm/gems/ruby-2.1.2/bin/git-bb:23:in `<main>'
    from /Users/lucas/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    from /Users/lucas/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by clauswitt** [comment]
Cannot seem to reproduce...

What os, what version of rubygems, and what version of rvm are you using? I will try to reproduce it...

// cw

**Comment by miloskroulik** [comment]
I have the exact same problem on Ubuntu 14.04. In my case, it's:

```
$ git bb repository create
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- daemons (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/bitbucket-cli-0.0.2/bin/git-bb:3:in `<top (required)>'
    from /usr/local/bin/git-bb:23:in `load'
    from /usr/local/bin/git-bb:23:in `<main>'
```

**Comment by miloskroulik** [comment]
The problem was solved by `sudo gem install daemons`

**Comment by clauswitt** [comment]
Hi

Apparently one of the dependencies of this library requires daemons without stating it as a requirement of the library. 

I have added daemons as a dependency: https://github.com/clauswitt/bitbucket-cli/commit/bd6a12eec5e97b859213b7f3554175768733ccbb

And released a new version of the gem: https://rubygems.org/gems/bitbucket-cli/versions/0.0.3

You can test it by removing the existing gem, and the daemons gem - and install again: 

```
gem uninstall bitbucket-cli
gem uninstall daemons
gem install bitbucket-cli
```
